style = "compact"

enter_accept = false
authors = ["$all-user"]
filter_mode_shell_up_key_binding = "directory"

keymap_mode = "vim-normal"
keymap_cursor = { vim_insert = "blink-block", vim_normal = "steady-block" }
[keymap.vim-normal]
"h" = "cursor-left"
"t" = "select-next"
"n" = "select-previous"
"s" = "cursor-right"
"y" = "copy"
"q" = "exit"

[ui]
columns = ["directory", "datetime", "user", "exit", "command"]
